### ISSUE TITLE
About no context network.

### ISSUE THREAD

**Issue by jjlinghu** [FiveLu/stream3dppe#1]
Hi, thanks for your sharing work!
Can you tell me why you do not utilize context network like 3dppe in PETR. Is it abandoned due to poor performance? If yes, what do you think is the main reason for the poor performance.
Looking forward to your reply, thanks!

**Comment by FiveLu** [comment]
Sorry for the late reply. At first, we used the `CameraAwareDepthNet`, but it didn't get a performance boost (the same as w/o 3dppe). Then I thought about it while verifying the code, does it make sense to use intrinsic and extrinsic to learn the channel attention weights? If you've done innovation based on StreamPETR, you will  notice that the training is unstable (gradient explosion is a very common ). So, we use no context image feats as an attempt and that works（`CameraAwareDepthNetV3`）. I don't know the deeper cause and mechanism.

**Comment by FiveLu** [comment]
> > Sorry for the late reply. At first, we used the `CameraAwareDepthNet`, but it didn't get a performance boost (the same as w/o 3dppe). Then I thought about it while verifying the code, does it make sense to use intrinsic and extrinsic to learn the channel attention weights? If you've done innovation based on StreamPETR, you will notice that the training is unstable (gradient explosion is a very common ). So, we use no context image feats as an attempt and that works（`CameraAwareDepthNetV3`）. I don't know the deeper cause and mechanism.
> 
> Thank you for your careful reply! I also noticed that the training of streampetr is not stable and the information you provided are useful for me! In addition, why we don't share the `3D Point PE Encoder` for the `Learnable 3D Initial Points` and `coords3d`, e.g. `share_pe_encoder=True`. I am doing some replicate experiment about works. If I refine and enhance the depth map in a more meticulous and reliable way, I can achieve performance that is closer to using ground truth supervision, is it right? I intend to delve into deeper research regarding depth maps, could you please some advice if you have. I apologize for disturbing you so late. Looking forward to your response in tomorrow.

1  Due to time constraints and lack of resources, we forgot to add the `share_pe_encoder`. Theoretically it will work ,you can try it!
2 Right! According to my knowledge, to do a better depth estimation on nuscenes can be considered in two directions, temporal or mono depth estimation. Some references for you, but are not limited to, [bev-io](https://arxiv.org/pdf/2305.16829) and [bevstereo](https://arxiv.org/abs/2209.10248).

**Comment by jjlinghu** [comment]
I'm so grateful for your, thanks again!
